[package]
name = "os-rs-gui"
version = "0.1.0"
authors = ["Jonathan Yaeger <jmyaeger@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
console_error_panic_hook = "0.1"
dioxus = { version = "0.7.9", features = ["router"] }
dioxus-logger = "0.7.2"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
getrandom = { version = "0.3.3", features = ["wasm_js"] }
gloo-net = "0.6"
gloo-timers = { version = "0.3.0", features = ["futures"] }
js-sys = "0.3"
log = "0.4.27"
osrs = { git = "https://github.com/jmyaeger/os-rs" }
plotly = "0.14.0"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1"
strum = "0.27"
strum_macros = "0.27"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "DedicatedWorkerGlobalScope",
    "Document",
    "Element",
    "ErrorEvent",
    "MessageEvent",
    "Window",
    "Worker",
    "WorkerOptions",
    "WorkerType",
]

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.android-dev]
inherits = "dev"

[profile.web-release]
inherits = "release"
debug = 0
strip = "debuginfo"
