[application]
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "os-rs-gui"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# Proxy configuration for OSRS hiscores API
[[web.proxy]]
backend = "https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws"
